# Site settings
title: Decolonizing the Geosciences, a student-led seminar
email: tide.eaps@gmail.com
author: Julia Wilcots et al.
description: "Decolonizing the Geosciences Seminar. Organized by Mara Freilich, Michaela Fendrock, Lyssa Freese, Meghana Ranganathan, and Julia Wilcots"
baseurl: "/TIDE-seminar"
url: "http://juliawilcots.github.io"

name: Julia Wilcots
markdown: kramdown
permalink: /journal/c34a44972dede8b45feb18a1f9a950e51bf341be/:year/:month/:day/:title
